name: PHPUnit

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: 'ubuntu-22.04'
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --configuration=phpunit.xml --no-coverage
